export const imageAssets = {
  heroHorizon: "/images/hero-horizon.png",
  projectDashboard: "/images/project-dashboard.png",
  clientAvatar: "/images/client-avatar.png",
  teamCollaboration: "/images/team-collaboration.jpg",
  capabilitiesBranding: "/images/capabilities-branding.jpg",
  capabilityUiux: "/images/capability-uiux.jpg",
  capabilityWebDevelopment: "/images/capability-web-development.jpg",
  capabilitySoftware: "/images/capability-software.jpg",
  capabilityMobile: "/images/capability-mobile.jpg",
  capabilityMaintenance: "/images/capability-maintenance.jpg",
  capabilityMarketing: "/images/capability-marketing.jpg",
  aboutTeam: "/images/about-team.jpg",
  aboutCapabilities: "/images/about-capabilities.jpg",
  aboutCaseOne: "/images/about-case-1.jpg",
  aboutCaseTwo: "/images/about-case-2.jpg",
  aboutCaseThree: "/images/about-case-3.jpg",
  aboutCaseFour: "/images/about-case-4.jpg",
} as const;
